# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thiamsu', '0002_song_original_lyrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveSmallIntegerField()),
                ('lang', models.CharField(choices=[('TL', '全羅'), ('HZ', '全漢')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thiamsu.Song')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveSmallIntegerField()),
                ('lang', models.CharField(choices=[('TL', '全羅'), ('HZ', '全漢')], max_length=2)),
                ('content', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thiamsu.Song')),
            ],
        ),
        migrations.AddField(
            model_name='approvedtranslation',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thiamsu.Translation'),
        ),
        migrations.AlterUniqueTogether(
            name='approvedtranslation',
            unique_together=set([('song', 'line_no', 'lang')]),
        ),
    ]
