# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thiamsu', '0004_auto_20171111_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='生難詞', max_length=100)),
                ('reference_url', models.CharField(help_text='參考網址', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='composer',
            field=models.CharField(default='', help_text='作曲人', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='lyricist',
            field=models.CharField(default='', help_text='作詞人', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='readonly',
            field=models.BooleanField(default=False, help_text='鎖定編修'),
        ),
        migrations.AddField(
            model_name='newword',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thiamsu.Song'),
        ),
        migrations.AlterUniqueTogether(
            name='newword',
            unique_together=set([('song', 'content', 'reference_url')]),
        ),
    ]
