# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thiamsu', '0007_auto_20171112_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='hanlo_performer',
            field=models.CharField(default='hanlo_performer', help_text='演唱人（台文）', max_length=100),
            preserve_default=False,
        ),
    ]
