# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thiamsu', '0012_auto_20171126_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='performer_alias',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='song',
            name='title_alias',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
