# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thiamsu', '0014_song_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='song_progress'),
        ),
    ]
