# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("thiamsu", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="song",
            name="original_lyrics",
            field=models.TextField(default="", help_text="原文歌詞"),
        )
    ]
