# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 13:53
from __future__ import unicode_literals

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("thiamsu", "0011_auto_20171124_1827")]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="youtube_url",
            field=embed_video.fields.EmbedVideoField(verbose_name="song_youtube_url"),
        )
    ]
