# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 16:17
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("thiamsu", "0013_auto_20171126_1403")]

    operations = [
        migrations.AddField(
            model_name="song",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="song_created_at",
            ),
            preserve_default=False,
        )
    ]
