# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("user", "0003_group_advance_user")]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "profile", "verbose_name_plural": "profiles"},
        )
    ]
