name: Deploy Python package to Azure Web App
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    environment: Azure
    steps:
      - uses: actions/checkout@v2

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to prod for Tags
        if: contains(github.ref, 'refs/tags/')
        run: make deploy/backend env=prod

      - name: Deploy to stage for Branch main or PR
        if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
        run: make deploy/backend env=stage

      - name: Logout
        run: make azure/logout
