name: Deploy Python package to Azure Web App
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to prod for Tags
        if: contains(github.ref, 'refs/tags/')
        run: make azure/deploy env=prod

      - name: Deploy to stage for Branch main or PR
        if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
        run: make azure/deploy env=stage

      - name: Logout
        run: az logout
